=== swmuir/xxxxx/trunk/ncpdp/models/org.ncpdp.uml.functions/schemas/transport.xsd
<?xml version="1.0" encoding="UTF-8"?><!--

Copyright (c) 2007, 2008, 2009, 2010 NCPDP. All rights reserved. This work is owned by National Council for Prescription Drug Programs, Inc., 924Ø E. Raintree Drive, Scottsdale, AZ 8526Ø, (48Ø) 477-1ØØØ, ncpdp@ncpdp.org, and protected by the copyright laws of the United States. 17 U.S.C. §1Ø1, et. seq. Permission is given to Council members to copy and use the work or any part thereof in connection with the business purposes of the Council members.   

The work may not be changed or altered. The work may not be sold, used or exploited for commercial purposes. This permission may be revoked by National Council for Prescription Drug Programs, Inc., at any time. The National Council for Prescription Drugs Programs, Inc. is not responsible for any errors or damage as a result of the use of the work.
NCPDP recognizes the confidentiality of certain information exchanged electronically through the use of its standards. Users should be familiar with the federal, state, and local laws, regulations and codes requiring confidentiality of this information and should utilize the standards accordingly.

NOTICE: In addition, this NCPDP Standard contains certain data fields and elements that may be completed by users with the proprietary information of third parties. The use and distribution of third parties' proprietary information without such third parties' consent, or the execution of a license or other agreement with such third party, could subject the user to numerous legal claims. All users are encouraged to contact such third parties to determine whether such information is proprietary and if necessary, to consult with legal counsel to make arrangements for the use and distribution of such proprietary information.


--><xsd:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.ncpdp.org/schema/Transport" version="201008" xmlns:SCRIPT="http://www.ncpdp.org/schema/SCRIPT" xmlns:datatypes="http://www.ncpdp.org/schema/datatypes" xmlns:ecl="http://www.ncpdp.org/schema/ecl" xmlns:specialized="http://www.ncpdp.org/schema/specialized" xmlns:transport="http://www.ncpdp.org/schema/Transport" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:import namespace="http://www.ncpdp.org/schema/datatypes" schemaLocation="datatypes.xsd"/>
  <xsd:import namespace="http://www.ncpdp.org/schema/ecl" schemaLocation="ecl.xsd"/>
  <xsd:import namespace="http://www.ncpdp.org/schema/SCRIPT" schemaLocation="script.xsd"/>
  <xsd:import namespace="http://www.ncpdp.org/schema/specialized" schemaLocation="specialized.xsd"/>
  <!-- ================================================== -->
  <!-- =====  Element Declarations  -->
  <!-- ================================================== -->
  <xsd:element name="Message" type="transport:MessageType"/>
  <!-- ================================================== -->
  <!-- =====  Complex Type Definitions  -->
  <!-- ================================================== -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  BodyType  <<choice>>  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="BodyType">
    <xsd:choice>
      <xsd:element name="Status" type="transport:Status"/>
      <xsd:element name="Error" type="transport:Error"/>
      <xsd:element name="Verify" type="transport:Verify"/>
      <xsd:element name="GetMessage" type="transport:GetMessage"/>
      <xsd:element name="PasswordChange" type="transport:PasswordChange"/>
      <xsd:element name="CancelRx" type="SCRIPT:CancelRx"/>
      <xsd:element name="CancelRxResponse" type="SCRIPT:CancelRxResponse"/>
      <xsd:element name="Census" type="specialized:Census"/>
      <xsd:element name="DrugAdminstration" type="SCRIPT:DrugAdminstration"/>
      <xsd:element name="NewRx" type="SCRIPT:NewRx"/>
      <xsd:element name="MTMServIceRequest" type="specialized:MTMServiceRequest"/>
      <xsd:element name="MTMServiceResponse" type="specialized:MTMServiceResponse"/>
      <xsd:element name="RefillRequest" type="SCRIPT:RefillRequest"/>
      <xsd:element name="RefillResponse" type="SCRIPT:RefillResponse"/>
      <xsd:element name="Resupply" type="SCRIPT:Resupply"/>
      <xsd:element name="RxChangeRequest" type="SCRIPT:RxChangeRequest"/>
      <xsd:element name="RxChangeResponse" type="SCRIPT:RxChangeResponse"/>
      <xsd:element name="RxFill" type="SCRIPT:RxFill"/>
      <xsd:element name="RxHistoryRequest" type="SCRIPT:RxHistoryRequest"/>
      <xsd:element name="RxHistoryResponse" type="SCRIPT:RxHistoryResponse"/>
    </xsd:choice>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  Error  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="Error">
    <xsd:sequence>
      <xsd:element name="Code" type="ecl:TransactionErrorCode"/>
      <xsd:element maxOccurs="10" minOccurs="0" name="DescriptionCode" type="ecl:DescriptionCode"/>
      <xsd:element minOccurs="0" name="Description" type="xsd:string"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  GetMessage  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="GetMessage">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="ReturnReceipt" type="datatypes:an..3"/>
      <xsd:element minOccurs="0" name="RequestReferenceNumber" type="datatypes:an..35"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  HeaderType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="HeaderType">
    <xsd:sequence>
      <xsd:element name="To">
        <xsd:annotation>
          <xsd:documentation>This field contains the identification number of the receiver. </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="datatypes:MailAddressType">
              <xsd:attribute name="Qualifier">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="P|C|M|D|ZZZ"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:attribute>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="From">
        <xsd:complexType>
          <xsd:simpleContent>
            <xsd:extension base="datatypes:MailAddressType">
              <xsd:attribute name="Qualifier">
                <xsd:simpleType>
                  <xsd:restriction base="xsd:string">
                    <xsd:pattern value="P|C|M|D|ZZZ"/>
                  </xsd:restriction>
                </xsd:simpleType>
              </xsd:attribute>
            </xsd:extension>
          </xsd:simpleContent>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="MessageID" type="datatypes:an..35M">
        <xsd:annotation>
          <xsd:documentation>Trace number. A unique reference identifier for the transmission, generated from the sender of the request and the sender of the response. When generated from the sender, it is then echoed back in the response message in the field RelatesToMessageID. The value in this field must be present in RelatesToMessageID on subsequent transactions (such as RefillRequest, CancelRx, etc) to tie back to an original transmission. </xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs="0" name="RelatesToMessageID" type="datatypes:an..35">
        <xsd:annotation>
          <xsd:documentation>See Imp Guide for more info. On a direct response transaction (such as Error, Status, RxHistoryResponse) or a subsequent follow up response (such as RxChangeResponse, RefillResponse, CancelRxResponse, MTMServiceResponse) or a subsequent follow up transaction (such as RxFill, Verify), this field is mandatory and is used to link the original message (MessageID) from request to the response or to the subsequent follow up transaction. 
On the CancelRx and NewRx messages used in the long term care order change process, this field is mandatory and contains the prescribing system’s order ID associated with the original prescription.
On requests (such as RefillRequest, CancelRx, RxChangeRequest), this field can only be sent if the message it relates to was electronic. For example, if the prescription was via paper or telephone, a subsequent refill request message would not have a relates to identifier. 
On other transactions that do not have a paired follow up message (such as NewRx, PasswordChange, GetMessage, Census), this field is an optional secondary identifier based on trading partner agreements or need of the originating system.
</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SentTime" type="datatypes:UtcDateType">
        <xsd:annotation>
          <xsd:documentation>The date of the transmission.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs="0" name="Security" type="transport:SecurityType"/>
      <xsd:element name="SenderSoftware" type="transport:SenderSoftwareType">
        <xsd:annotation>
          <xsd:documentation>Identifies the entity responsible that generated the transaction.
Note: For Status, Error, Verify transactions – contains software identification of the entity creating the response.&lt;/xs:documentation&gt;
				</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element minOccurs="0" name="Mailbox" type="transport:MailboxType"/>
      <xsd:element minOccurs="0" name="TestMessage" type="datatypes:n1"/>
      <xsd:element minOccurs="0" name="RxReferenceNumber" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="TertiaryIdentifier" type="datatypes:an..3"/>
      <xsd:element minOccurs="0" name="PrescriberOrderNumber" type="datatypes:an..35"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  MailboxType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="MailboxType">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="MailboxID" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="DeliveredID" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="AdditionalTraceNumber" type="datatypes:an..3"/>
      <xsd:element minOccurs="0" name="AcknowledgementID" type="datatypes:an..35"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  MessageType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="MessageType">
    <xsd:sequence>
      <xsd:element name="Header" type="transport:HeaderType"/>
      <xsd:element name="Body" type="transport:BodyType"/>
    </xsd:sequence>
    <xsd:attribute name="DatatypesVersion" type="xsd:string" use="required"/>
    <xsd:attribute name="TransportVersion" type="xsd:string" use="required"/>
    <xsd:attribute name="TransactionDomain" type="ecl:TransactionDomainVersionQualifierCode" use="required"/>
    <xsd:attribute name="TransactionVersion" type="xsd:string" use="required"/>
    <xsd:attribute name="StructuresVersion" type="xsd:string" use="required"/>
    <xsd:attribute name="ECLVersion" type="xsd:string" use="required"/>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  PasswordChange  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="PasswordChange">
    <xsd:sequence>
      <xsd:element name="Request" type="transport:PasswordRequestType"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  PasswordRequestType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="PasswordRequestType">
    <xsd:sequence>
      <xsd:element name="OldPassword" type="datatypes:anM"/>
      <xsd:element name="NewPassword" type="datatypes:anM"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  Release  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="Release">
    <xsd:attribute name="Name" type="xsd:string" use="required"/>
    <xsd:attribute name="version" type="xsd:string" use="required"/>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  SecurityIdentificationType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="SecurityIdentificationType">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="SecondaryIdentification" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="TertiaryIdentification" type="datatypes:an..35"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  SecurityType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="SecurityType">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="UsernameToken" type="transport:UsernameTokenType"/>
      <xsd:element name="Sender" type="transport:SecurityIdentificationType"/>
      <xsd:element name="Receiver" type="transport:SecurityIdentificationType"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  SenderSoftwareType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="SenderSoftwareType">
    <xsd:sequence>
      <xsd:element name="SenderSoftwareDeveloper" type="datatypes:an..35M">
        <xsd:annotation>
          <xsd:documentation>The text field that identifies the entity responsible for the software that generated the transaction.  The developer may be a software vendor or, if the software was developed “in-house”, the developer is the entity actually sending the transaction (e.g., a chain).  The value transmitted is determined by the Sender Software Developer.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SenderSoftwareProduct" type="datatypes:an..35M">
        <xsd:annotation>
          <xsd:documentation>The text field that identifies the software developer’s product, as determined by the software developer.</xsd:documentation>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="SenderSoftwareVersionRelease" type="datatypes:an..50M"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  Status  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="Status">
    <xsd:sequence>
      <xsd:element name="Code">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="000|001|002|003|005|010"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
      <xsd:element maxOccurs="10" minOccurs="0" name="DescriptionCode" type="ecl:DescriptionCode"/>
      <xsd:element minOccurs="0" name="Description" type="datatypes:an..70"/>
      <xsd:element minOccurs="0" name="PrescriptionDeliveryMethod">
        <xsd:simpleType>
          <xsd:restriction base="xsd:string">
            <xsd:pattern value="1|2"/>
          </xsd:restriction>
        </xsd:simpleType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  UsernameTokenType  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="UsernameTokenType">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="Username" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="Password" type="datatypes:PasswordType"/>
      <xsd:element minOccurs="0" name="Nonce" type="datatypes:an..35"/>
      <xsd:element minOccurs="0" name="Created" type="datatypes:UtcDateType"/>
    </xsd:sequence>
  </xsd:complexType>
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <!--  Verify  -->
  <!-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ -->
  <xsd:complexType name="Verify">
    <xsd:sequence>
      <xsd:element minOccurs="0" name="VerifyStatus">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="Code">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:pattern value="010"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
            <xsd:element minOccurs="0" name="Description" type="datatypes:an..70"/>
            <xsd:element minOccurs="0" name="PrescriptionDeliveryMethod">
              <xsd:simpleType>
                <xsd:restriction base="xsd:string">
                  <xsd:pattern value="1|2"/>
                </xsd:restriction>
              </xsd:simpleType>
            </xsd:element>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
  <xsd:annotation>
    <xsd:documentation>The NCPDP transport.xsd defines the envelope structures for the transactions and highest level 
elements for each transaction.</xsd:documentation>
  </xsd:annotation>
</xsd:schema>

=== swmuir/xxxxx/org.ncpdp.uml.functions/schemas/NewRx1fNoMoreMail.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2010 (http://www.altova.com)-->
<transport:Message StructuresVersion="String" ECLVersion="String" DatatypesVersion="String" TransactionDomain="SCRIPT" TransactionVersion="String" TransportVersion="String" xsi:schemaLocation="http://www.ncpdp.org/schema/Transport transport.xsd" xmlns:transport="http://www.ncpdp.org/schema/Transport" xmlns:datatypes="http://www.ncpdp.org/schema/datatypes" xmlns:SCRIPT="http://www.ncpdp.org/schema/SCRIPT " xmlns:structures="http://www.ncpdp.org/schema/structures" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<transport:Header>
		<transport:To Qualifier="P">7701630</transport:To>
		<transport:From Qualifier="M">111111</transport:From>
		<transport:MessageID>66666684</transport:MessageID>
		<transport:RelatesToMessageID>A25</transport:RelatesToMessageID>
		<transport:SentTime>2010-10-01T08:20:26</transport:SentTime>
		<transport:SenderSoftware>
			<transport:SenderSoftwareDeveloper>SWITCH123</transport:SenderSoftwareDeveloper>
			<transport:SenderSoftwareProduct>ROUTEA</transport:SenderSoftwareProduct>
			<transport:SenderSoftwareVersionRelease>55</transport:SenderSoftwareVersionRelease>
		</transport:SenderSoftware>
	</transport:Header>
	<transport:Body>
		<transport:Status>
				<transport:Code>002</transport:Code>
	</transport:Status>
</transport:Body>
</transport:Message>

=== swmuir/xxxxx/branches/Branch-Aug-2012-Ballot/org.ncpdp.uml.functions/schemas/Untitled22.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2012 rel. 2 (x64) (http://www.altova.com)-->
<transport:Message DatatypesVersion="!" TransportVersion="!" TransactionDomain="Specialized" TransactionVersion="!" StructuresVersion="!" ECLVersion="!" xsi:schemaLocation="http://www.ncpdp.org/schema/Transport transport.xsd" xmlns:transport="http://www.ncpdp.org/schema/Transport" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<transport:Header>
		<transport:To Qualifier="D">!</transport:To>
		<transport:From Qualifier="C">!</transport:From>
		<transport:MessageID>!</transport:MessageID>
		<transport:RelatesToMessageID>!</transport:RelatesToMessageID>
		<transport:SentTime>2001-12-17T09:30:47Z</transport:SentTime>
		<transport:Security>
			<transport:UsernameToken>
				<transport:Username>!</transport:Username>
				<transport:Password Type="PasswordDigest">String</transport:Password>
				<transport:Nonce>!</transport:Nonce>
				<transport:Created>2001-12-17T09:30:47Z</transport:Created>
			</transport:UsernameToken>
			<transport:Sender>
				<transport:SecondaryIdentification>!</transport:SecondaryIdentification>
				<transport:TertiaryIdentification>!</transport:TertiaryIdentification>
			</transport:Sender>
			<transport:Receiver>
				<transport:SecondaryIdentification>!</transport:SecondaryIdentification>
				<transport:TertiaryIdentification>!</transport:TertiaryIdentification>
			</transport:Receiver>
		</transport:Security>
		<transport:SenderSoftware>
			<transport:SenderSoftwareDeveloper>!</transport:SenderSoftwareDeveloper>
			<transport:SenderSoftwareProduct>!</transport:SenderSoftwareProduct>
			<transport:SenderSoftwareVersionRelease>!</transport:SenderSoftwareVersionRelease>
		</transport:SenderSoftware>
		<transport:Mailbox>
			<transport:MailboxID>!</transport:MailboxID>
			<transport:DeliveredID>!</transport:DeliveredID>
			<transport:AdditionalTraceNumber>!</transport:AdditionalTraceNumber>
			<transport:AcknowledgementID>!</transport:AcknowledgementID>
		</transport:Mailbox>
		<transport:TestMessage>0</transport:TestMessage>
		<transport:RxReferenceNumber>!</transport:RxReferenceNumber>
		<transport:TertiaryIdentifier>!</transport:TertiaryIdentifier>
		<transport:PrescriberOrderNumber>!</transport:PrescriberOrderNumber>
	</transport:Header>
	<transport:Body>
		<transport:Status>
			<transport:Code>001</transport:Code>
			<transport:DescriptionCode>008</transport:DescriptionCode>
			<transport:Description>\!</transport:Description>
			<transport:PrescriptionDeliveryMethod>2</transport:PrescriptionDeliveryMethod>
		</transport:Status>
	</transport:Body>
</transport:Message>
